In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])
print(x)
print(y)

[1 2 3 4]
[5 6 7 8]


In [3]:
print(x + y)

[ 6  8 10 12]


In [4]:
print(np.add(x, y))

[ 6  8 10 12]


In [6]:
print(x - y)
print(np.subtract(x, y))

[-4 -4 -4 -4]
[-4 -4 -4 -4]


In [7]:
print(x * y)
print(np.multiply(x, y))

[ 5 12 21 32]
[ 5 12 21 32]


In [8]:
print(x / y)
print(np.divide(x, y))

[ 0.2         0.33333333  0.42857143  0.5       ]
[ 0.2         0.33333333  0.42857143  0.5       ]


In [9]:
x = np.array([1, 2, 3, 4]).reshape(2, 2)
print(x)

[[1 2]
 [3 4]]


In [10]:
y = np.array([5, 6, 7, 8]).reshape(2, 2)
print(y)

[[5 6]
 [7 8]]


In [11]:
print(np.sqrt(x))

[[ 1.          1.41421356]
 [ 1.73205081  2.        ]]


In [12]:
print(np.exp(x))

[[  2.71828183   7.3890561 ]
 [ 20.08553692  54.59815003]]


In [13]:
print(np.power(x, 2))

[[ 1  4]
 [ 9 16]]


In [14]:
print("average: {}".format(x.mean()))

average: 2.5


In [15]:
print("average of columns: {}".format(x.mean(axis=0)))

average of columns: [ 2.  3.]


In [16]:
print("average of rows: {}".format(x.mean(axis=1)))

average of rows: [ 1.5  3.5]


In [17]:
print("sum of all: {}".format(x.sum()))

sum of all: 10


In [18]:
print("sum of columns: {}".format(x.sum(axis=0)))

sum of columns: [4 6]


In [19]:
print("sum of rows: {}".format(x.sum(axis=1)))

sum of rows: [3 7]


In [20]:
x.std()

1.1180339887498949

In [21]:
np.median(x)

2.5

In [22]:
x.max()

4

In [23]:
x.min()

1

In [24]:
print(x)

[[1 2]
 [3 4]]


In [25]:
print(x + 3)

[[4 5]
 [6 7]]


In [26]:
print(x)

[[1 2]
 [3 4]]


In [27]:
print(x - 3)
print(x * 3)
print(x / 3)

[[-2 -1]
 [ 0  1]]
[[ 3  6]
 [ 9 12]]
[[ 0.33333333  0.66666667]
 [ 1.          1.33333333]]


In [28]:
y = np.arange(9).reshape(3, 3)
print(y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [29]:
x= np.arange(3)
print(x)

[0 1 2]


In [30]:
print(y + x)

[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]


In [31]:
print(x + y)

[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]
