In [1]:
import numpy as np

In [2]:
x = np.arange(25).reshape(5, 5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [4]:
print(x[x > 10])

[11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [7]:
print(x[x <= 7])

[0 1 2 3 4 5 6 7]


In [9]:
print(x[(x > 10) & (x < 17)])

[11 12 13 14 15 16]


In [10]:
x[(x > 10) & (x < 17)] = -1
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 -1 -1 -1 -1]
 [-1 -1 17 18 19]
 [20 21 22 23 24]]


In [14]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([6, 7, 2, 8, 4])

print(np.intersect1d(x, y))
print(np.setdiff1d(x, y))
print(np.setdiff1d(y, x))
print(np.union1d(x, y))

[2 4]
[1 3 5]
[6 7 8]
[1 2 3 4 5 6 7 8]


In [17]:
x = np.random.randint(1, 11, size=(10, ))
print(x)

[10  2  2  2 10  8  1  5  3  7]


In [18]:
print(np.sort(x))
print(x)

[ 1  2  2  2  3  5  7  8 10 10]
[10  2  2  2 10  8  1  5  3  7]


In [19]:
x.sort()
print(x)

[ 1  2  2  2  3  5  7  8 10 10]


In [20]:
x = np.random.randint(1, 11, size=(5, 5))
print(x)

[[ 9  1  1  6  8]
 [ 9  8  6  9  8]
 [ 1  3 10  5  2]
 [ 6  3  7  1  1]
 [ 7  3  7  1  8]]


In [21]:
print(np.sort(x, axis=0))

[[ 1  1  1  1  1]
 [ 6  3  6  1  2]
 [ 7  3  7  5  8]
 [ 9  3  7  6  8]
 [ 9  8 10  9  8]]


In [23]:
print(np.sort(x, axis=1))

[[ 1  1  6  8  9]
 [ 6  8  8  9  9]
 [ 1  2  3  5 10]
 [ 1  1  3  6  7]
 [ 1  3  7  7  8]]


In [24]:
print(np.sort(x))

[[ 1  1  6  8  9]
 [ 6  8  8  9  9]
 [ 1  2  3  5 10]
 [ 1  1  3  6  7]
 [ 1  3  7  7  8]]
