In [1]:
import numpy as np

In [3]:
x = np.zeros((3, 4), dtype=int)
print(x)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [4]:
print('dtype: {}'.format(x.dtype))

dtype: int64


In [5]:
x = np.ones((4, 5))
print(x)

[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]


In [7]:
x = np.full((4, 3), 5)
print(x)

[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]


In [9]:
x = np.eye(5)
print(x)

[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]


In [10]:
x = np.diag([10, 20, 30, 40, 50])
print(x)

[[10  0  0  0  0]
 [ 0 20  0  0  0]
 [ 0  0 30  0  0]
 [ 0  0  0 40  0]
 [ 0  0  0  0 50]]


In [12]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [13]:
x = np.arange(4, 10)
print(x)

[4 5 6 7 8 9]


In [14]:
x = np.arange(1, 14, 3)
print(x)

[ 1  4  7 10 13]


In [18]:
x = np.linspace(0, 25, 10)
print(x)

[  0.           2.77777778   5.55555556   8.33333333  11.11111111
  13.88888889  16.66666667  19.44444444  22.22222222  25.        ]


In [19]:
x = np.linspace(0, 25, 10, endpoint=False)
print(x)

[  0.    2.5   5.    7.5  10.   12.5  15.   17.5  20.   22.5]


In [20]:
x = np.arange(20)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [22]:
x = np.reshape(x, (4, 5))
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [23]:
x = np.reshape(x, (2, 10))
print(x)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [24]:
x = np.reshape(x, (10, 2))
print(x)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [26]:
y = np.arange(20).reshape((10, 2))
print(y)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [27]:
x = np.random.random((3, 3))
print(x)

[[ 0.66231668  0.09864813  0.67696901]
 [ 0.21542014  0.14975425  0.68052005]
 [ 0.33312276  0.12571403  0.82841221]]


In [30]:
y = np.random.randint(4, 15, (3, 2))
print(y)

[[10 14]
 [ 9 10]
 [11  6]]


In [32]:
x = np.random.normal(0, 0.1, size=(20, 20))
print(x)

[[  5.20400358e-02   2.74349130e-02  -1.63925199e-03  -2.67048838e-01
   -2.01015486e-02  -3.14722305e-02   3.35283362e-02   1.27266303e-01
    8.13352378e-02   4.54404510e-02   8.46112049e-02   9.90199722e-02
    7.29657351e-02   1.54792620e-02  -8.90480975e-02   1.74689059e-01
   -8.43596953e-03  -1.15923737e-01   8.76652093e-02  -8.03792285e-02]
 [  2.44721139e-01   1.23741871e-01   4.26318868e-03   6.46803901e-02
    7.64498223e-02  -5.72283854e-02  -1.22105744e-02  -1.22641562e-01
    2.19881563e-01   1.73027651e-01  -5.61882499e-02   4.39990983e-02
    1.99027566e-01   8.64049255e-02   6.00333164e-02  -9.07312515e-02
    2.14625756e-01  -1.29798548e-01  -3.40788822e-02  -1.33730602e-01]
 [ -7.77986423e-02  -1.02313453e-01  -3.07490470e-01  -4.59164647e-02
   -1.06084487e-01  -6.04414343e-02  -5.85353261e-02   1.18761424e-02
   -1.43205793e-01   9.94879142e-02   5.43620032e-02   7.04724168e-02
    1.63693934e-01  -4.70421220e-02  -4.97619760e-02   2.37446870e-02
   -3.77830434e-02