In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3, 4, 5])

In [3]:
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
x.dtype

dtype('int64')

In [5]:
x.shape

(5,)

In [9]:
y = np.array([[1,2,3], [4,5,6], [7,8,9],[10,11,12]])
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [8]:
y.shape

(4, 3)

In [10]:
y.size

12

In [11]:
z = np.array(['Hello', 'World'])
print(z)

['Hello' 'World']


In [14]:
print('shape: {}'.format(z.shape))
print('type: {}'.format(type(z)))
print('dtype: {}'.format(z.dtype))

shape: (2,)
type: <class 'numpy.ndarray'>
dtype: <U5


In [15]:
mix = np.array([1, 2, 'World'])
print(mix)

['1' '2' 'World']


In [16]:
print('shape: {}'.format(mix.shape))
print('type: {}'.format(type(mix)))
print('dtype: {}'.format(mix.dtype))

shape: (3,)
type: <class 'numpy.ndarray'>
dtype: <U21


In [17]:
# downcasting
my_integers = np.array([1.5, 2.2, 3.7], dtype=np.int64)
print(my_integers)
print(my_integers.dtype)

[1 2 3]
int64


In [18]:
to_save = np.array([1, 2, 3, 4, 5])
np.save("my_array", to_save)

In [19]:
to_load = np.load("my_array.npy")
print(to_load)

[1 2 3 4 5]
