In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3, 4, 5])
print(x)

[1 2 3 4 5]


In [4]:
print('1st element: {}'.format(x[0]))
print('2nd element: {}'.format(x[1]))
print('3rd element: {}'.format(x[2]))

1st element: 1
2nd element: 2
3rd element: 3


In [5]:
print('1st element: {}'.format(x[-5]))
print('2nd element: {}'.format(x[-4]))
print('3rd element: {}'.format(x[-3]))

1st element: 1
2nd element: 2
3rd element: 3


In [6]:
x[3] = 20
print(x)

[ 1  2  3 20  5]


In [7]:
x = np.arange(1, 10).reshape(3, 3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
print('element at (0, 0): {}'.format(x[0, 0]))
print('2nd element (0, 1): {}'.format(x[0, 1]))
print('3rd element (2, 2): {}'.format(x[2, 2]))

element at (0, 0): 1
2nd element (0, 1): 2
3rd element (2, 2): 9


In [9]:
x[0, 0] = 20
print(x)

[[20  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [10]:
x = np.array([1, 2, 3, 4, 5])
print(x)

x = np.delete(x, [0, 4])
print(x)

[1 2 3 4 5]
[2 3 4]


In [11]:
y = np.arange(1, 10).reshape(3, 3)
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
w = np.delete(y, 0, axis=0)
print('\n', w)


 [[4 5 6]
 [7 8 9]]


In [14]:
v = np.delete(y, [0, 2], axis=1)
print('\n', v)


 [[2]
 [5]
 [8]]


In [15]:
x = np.array([1, 2, 3, 4, 5])
print(x)

x = np.append(x, 6)
print(x)

[1 2 3 4 5]
[1 2 3 4 5 6]


In [16]:
x = np.append(x, [7, 8])
print(x)

[1 2 3 4 5 6 7 8]


In [18]:
y = np.arange(1, 10).reshape(3, 3)
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
w = np.append(y, [[10, 11, 12]], axis = 0)
print(w)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [21]:
v = np.append(y, [[10],[11],[12]], axis = 1)
print(v)

[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


In [22]:
x = np.array([1, 2, 5, 6, 7])
print(x)

[1 2 5 6 7]


In [23]:
x = np.insert(x, 2, [3, 4])
print(x)

[1 2 3 4 5 6 7]


In [24]:
y = np.array([[1, 2, 3], [7, 8, 9]])
print(y)

[[1 2 3]
 [7 8 9]]


In [26]:
w = np.insert(y, 1, [4, 5, 6], axis = 0)
print(w)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [27]:
v = np.insert(y, 1, 5, axis = 1)
print(v)

[[1 5 2 3]
 [7 5 8 9]]


In [28]:
x = np.array([1, 2])
print(x)

[1 2]


In [29]:
y = np.array([[3, 4], [5, 6]])
print(y)

[[3 4]
 [5 6]]


In [30]:
z = np.vstack((x, y))
print(z)

[[1 2]
 [3 4]
 [5 6]]


In [31]:
z2 = np.vstack((y, x))
print(z2)

[[3 4]
 [5 6]
 [1 2]]


In [32]:
w = np.hstack((y, x.reshape(2, 1)))
print(w)

[[3 4 1]
 [5 6 2]]
