In [1]:
import numpy as np

In [3]:
x = np.arange(1, 21).reshape(4, 5)
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [4]:
z = x[1:4, 2:5]
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [5]:
z = x[1:, 2:]
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [7]:
z = x[:3, 2:]
print(z)

[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]


In [8]:
z = x[:, 2]
print(z)

[ 3  8 13 18]


In [9]:
z = x[2, :]
print(z)

[11 12 13 14 15]


In [10]:
z = x[:, 2:3]
print(z)

[[ 3]
 [ 8]
 [13]
 [18]]


In [11]:
z = x[:, 2:4]
print(z)

[[ 3  4]
 [ 8  9]
 [13 14]
 [18 19]]


In [12]:
z = x[1:, 2:]
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [13]:
z[2, 2] = 555
print(z)

[[  8   9  10]
 [ 13  14  15]
 [ 18  19 555]]


In [14]:
print(x)

[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19 555]]


In [15]:
x = np.arange(20).reshape(4, 5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [16]:
z = np.copy(x[1:, 2:])
print(z)

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [17]:
z[2, 2] = 555
print(z)

[[  7   8   9]
 [ 12  13  14]
 [ 17  18 555]]


In [18]:
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [19]:
indices = np.array([1, 3])
print(indices)

[1 3]


In [20]:
y = x[indices, :]
print(y)

[[ 5  6  7  8  9]
 [15 16 17 18 19]]


In [21]:
z = x[:, indices]
print(z)

[[ 1  3]
 [ 6  8]
 [11 13]
 [16 18]]


In [22]:
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [23]:
z = np.diag(x)
print(z)

[ 0  6 12 18]


In [24]:
z = np.diag(x, k = 1)
print(z)

[ 1  7 13 19]


In [25]:
z = np.diag(x, k = -1)
print(z)

[ 5 11 17]


In [28]:
x = np.array([[1,2,3],[5,2,8],[1,2,3]])
print(x)
print(np.unique(x))

[[1 2 3]
 [5 2 8]
 [1 2 3]]
[1 2 3 5 8]
